services:
  app:
    build: .
    environment:
      DISPLAY_WIDTH: "1600"
      DISPLAY_HEIGHT: "900"
      RUN_XTERM: "no"
      RUN_FLUXBOX: "yes"
      NGINX_PATHPORT: "yes"
    volumes:
      - /root/.config/mockoon
      - ./mockoon/storage:/root/.config/mockoon/storage
    ports:
      - ${MOCKOON_HOST:-127.0.0.1}:${MOCKOON_PORT:-3000}:3000
      - ${NOVNC_HOST:-127.0.0.1}:${NOVNC_PORT:-8080}:8080
      - ${NGINX_HOST:-127.0.0.1}:${NGINX_PORT:-80}:80
    healthcheck:
      test: wget http://localhost/users --spider || exit 1
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 5s
